# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Pull Request for Main Build

on: 
  pull_request:
    branches: [ "main" ]

jobs:
  main-build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout GCM Taskit
      uses: actions/checkout@v3
    - name: Checkout Taskit
      uses: actions/checkout@v3
      with:
        repository: HHS/ASPR-ms-taskit
        path: taskit
    - name: Checkout Util
      uses: actions/checkout@v3
      with:
        repository: HHS/ASPR-ms-util
        path: util
    - name: Checkout GCM
      uses: actions/checkout@v3
      with:
        repository: HHS/ASPR-8
        path: gcm
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build Util
      run: mvn clean install -DskipTests --file util/pom.xml
    - name: Build GCM
      run: mvn clean install -DskipTests --file gcm/pom.xml
    - name: Build Taskit
      run: mvn clean install -DskipTests --file taskit/pom.xml
    - name: Build GCM Taskit
      run: mvn clean install -Prelease --file protobuf/pom.xml